using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Shitmed.Antags.Abductor;
[GenerateTypedNameReferences]
public sealed partial class AbductorCameraConsoleWindow : FancyWindow
{
    public AbductorCameraConsoleWindow() => RobustXamlLoader.Load(this);
}
