using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Mapping;

[GenerateTypedNameReferences]
public sealed partial class MappingVisibilityWindow : FancyWindow
{
    public MappingVisibilityWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

