using Content.Client.InterfaceGuidelines;
using Content.Shared.InterfaceGuidelines;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client.Mapping;


[GenerateTypedNameReferences]
public sealed partial class MappingActionsButton : Button
{
    [Dependency] private readonly TypographyManager _typographyManager = null!;

    public string Icon { get => Label.Text ?? ""; set => Label.Text = value; }

    public MappingActionsButton()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Label.FontOverride = _typographyManager.GetSymbolsFont(
            filled: true,
            style: TextStyle.Title2,
            weight: FontWeight.SemiBold
        );
    }
}
