using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Chemistry.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class TransferAmountWindow : FancyWindow
    {
        public TransferAmountWindow()
        {
            RobustXamlLoader.Load(this);
        }
    }
}
