using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Logs;

[GenerateTypedNameReferences]
public sealed partial class AdminLogsWindow : FancyWindow
{
    public AdminLogsWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
