using Content.Shared.InterfaceGuidelines;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client.UserInterface.Controls;


[GenerateTypedNameReferences]
public sealed partial class FancyButton : ContainerButton
{
    public string? Text { get => ButtonLabel.Text; set => ButtonLabel.Text = value; }

    private readonly bool _inited;

    public FancyButton()
    {
        RobustXamlLoader.Load(this);

        _inited = true;

        UpdateAppearance();
    }

    protected override void DrawModeChanged()
    {
        base.DrawModeChanged();

        if (!_inited)
            return;

        UpdateAppearance();
    }

    private void UpdateAppearance() =>
        ButtonLabel.SetOnlyStyleClass(
            DrawMode == DrawModeEnum.Disabled
                ? UIStyleClasses.FancyButtonLabelDisabled
                : UIStyleClasses.FancyButtonLabel);
}
