using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client.UserInterface.Controls;


[GenerateTypedNameReferences]
public sealed partial class GlyphIconButton : ContainerButton
{
    public string Glyph
    {
        get => _glyph;
        set
        {
            _glyph = value;
            UpdateLabel();
        }
    }

    public string? HoverGlyph
    {
        get => _hoverGlyph;
        set
        {
            _hoverGlyph = value;
            UpdateLabel();
        }
    }

    private string  _glyph = "";
    private string? _hoverGlyph;

    private readonly bool _inited;

    public GlyphIconButton()
    {
        RobustXamlLoader.Load(this);

        _inited = true;
    }


    protected override void DrawModeChanged()
    {
        base.DrawModeChanged();

        UpdateLabel();
    }

    private void UpdateLabel()
    {
        if (!_inited)
            return;

        if (DrawMode == DrawModeEnum.Normal || HoverGlyph is null)
            ButtonLabel.Text = Glyph;
        else if (HoverGlyph is { } hoverGlyph)
            ButtonLabel.Text = hoverGlyph;
    }
}
