// Copyright (C) 2025 Igor Spichkin

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.

// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos.Piping.Binary.GasPipeAdapter;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client.Atmos.UI;


[GenerateTypedNameReferences]
public sealed partial class GasPipeAdapterWindow : FancyWindow
{
    public event Action<int>? OnInletLayerSelected;
    public event Action<int>? OnOutletLayerSelected;

    public GasPipeAdapterWindow()
    {
        RobustXamlLoader.Load(this);

        InletLayerSelector.OnLayerSelected  += layer => OnInletLayerSelected?.Invoke(layer);
        OutletLayerSelector.OnLayerSelected += layer => OnOutletLayerSelected?.Invoke(layer);
    }

    public void UpdateState(GasPipeAdapterUiState state)
    {
        InletLayerSelector.SetSelectedLayer(state.SelectedInletLayer);
        OutletLayerSelector.SetSelectedLayer(state.SelectedOutletLayer);
    }
}
