// Copyright (C) 2025 Igor Spichkin

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.

// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

using Content.Client.UserInterface.Controls;
using Content.Shared.InterfaceGuidelines;
using Content.Shared.Localizations;
using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;
using Robust.Shared.Utility;


namespace Content.Client.UserInterface.GlobalMenu.UI;


[GenerateTypedNameReferences]
public sealed partial class GlobalMenu : UIWidget
{
    private const string ChangeStyleAnimationKey = "ChangeStyleAnimationKey";

    private readonly GlobalMenuPopup  _popup = new();
    private readonly RectBox          _panel;
    private          LocalizedString? _currentCategory;

    [Animatable]
    public Color BackgroundColor
    {
        get => _panel.BackgroundColor;
        set => _panel.BackgroundColor = value;
    }

    [Animatable]
    public Color BorderColor
    {
        get => _panel.Borders!.Value.Color;
        set => _panel.Borders = _panel.Borders!.Value with { Color = value, };
    }

    [Animatable]
    public Color InsetBorderColor
    {
        get => _panel.InsetBorders!.Value.Color;
        set => _panel.InsetBorders = _panel.Borders!.Value with { Color = value, };
    }

    public event Action<LocalizedString, LocalizedString>? ItemPressed;

    public GlobalMenu()
    {
        RobustXamlLoader.Load(this);

        var defaultStyle = GlobalMenuStyle.Default;

        GlobalMenuPanel.PanelOverride = _panel = new()
        {
            Borders         = new(defaultStyle.Border, new(0.0f, 0.0f, 0.0f, 2.0f)),
            InsetBorders    = new(defaultStyle.InsetBorder, new(0.0f, 0.0f, 0.0f, 2.0f)),
            BackgroundColor = defaultStyle.Background
        };

        SetStyle(defaultStyle);

        _popup.OnPopupOpen += () =>
        {
            UserInterfaceManager.ModalRoot.AddChild(_popup);
        };
        _popup.OnPopupHide += () =>
        {
            _currentCategory = null;
            UserInterfaceManager.ModalRoot.RemoveChild(_popup);
        };
        _popup.ItemClicked += item =>
        {
            DebugTools.AssertNotNull(_currentCategory);

            ItemPressed?.Invoke(_currentCategory!.Value, item);
            _popup.Close();
        };
    }

    public void SetStyle(GlobalMenuStyle style)
    {
        if (HasRunningAnimation(ChangeStyleAnimationKey))
            StopAnimation(ChangeStyleAnimationKey);

        var currentPanel = (RectBox) GlobalMenuPanel.PanelOverride!;

        var anim = new Animation
        {
            Length = TimeSpan.FromSeconds(AnimationConstants.ControlFadeInDuration),
            AnimationTracks =
            {
                new AnimationTrackControlProperty
                {
                    Property = nameof(BackgroundColor),
                    KeyFrames =
                    {
                        new(currentPanel.BackgroundColor, 0.0f),
                        new(style.Background, AnimationConstants.ControlFadeInDuration)
                    }
                },
                new AnimationTrackControlProperty
                {
                    Property = nameof(BorderColor),
                    KeyFrames =
                    {
                        new(currentPanel.Borders!.Value.Color, 0.0f),
                        new(style.Border, AnimationConstants.ControlFadeInDuration)
                    }
                },
                new AnimationTrackControlProperty
                {
                    Property = nameof(InsetBorderColor),
                    KeyFrames =
                    {
                        new(currentPanel.InsetBorders!.Value.Color, 0.0f),
                        new(style.InsetBorder, AnimationConstants.ControlFadeInDuration)
                    }
                }
            }
        };

        PlayAnimation(anim, ChangeStyleAnimationKey);
    }

    public void Populate(IReadOnlyList<Category> categories)
    {
        Clear();

        foreach (var category in categories)
        {
            var categoryButton = new GlobalMenuCategoryButton(category.IsIcon)
            {
                Text = category.Name.ToString()
            };

            categoryButton.OnButtonDown += ev => OnCategoryPressed(ev, category);

            MenuContainer.AddChild(categoryButton);
        }
    }

    private void Clear() => MenuContainer.RemoveAllChildren();

    private void OnCategoryPressed(BaseButton.ButtonEventArgs ev, Category category)
    {
        _currentCategory = category.Name;

        var topLeft = ev.Button.GlobalRect.BottomLeft;

        topLeft.Y += 8;
        topLeft.X += 8;

        _popup.SetItems(category.Items);
        _popup.Open(UIBox2.FromDimensions(topLeft, new()));
    }

    public record struct Category(LocalizedString Name, List<GlobalMenuPopup.Item> Items, bool IsIcon);
}
