// Copyright (C) 2025 Igor Spichkin

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.

// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

using Content.Shared.Localizations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;


namespace Content.Client.UserInterface.GlobalMenu.UI;


[GenerateTypedNameReferences]
public sealed partial class GlobalMenu : UIWidget
{
    private readonly GlobalMenuPopup  _popup = new();
    private          LocalizedString? _currentCategory;

    public event Action<LocalizedString, LocalizedString>? ItemPressed;

    public GlobalMenu()
    {
        RobustXamlLoader.Load(this);

        _popup.OnPopupHide += () => _currentCategory = null;
        _popup.ItemClicked += item =>
        {
            DebugTools.AssertNotNull(_currentCategory);

            ItemPressed?.Invoke(_currentCategory!.Value, item);
            _popup.Close();
        };

        UserInterfaceManager.ModalRoot.AddChild(_popup);
    }

    public void Populate(IReadOnlyList<Category> categories)
    {
        Clear();

        foreach (var category in categories)
        {
            var categoryButton = new GlobalMenuCategoryButton(category.IsIcon)
            {
                Text = category.Name.ToString()
            };

            categoryButton.OnButtonDown += ev => OnCategoryPressed(ev, category);

            MenuContainer.AddChild(categoryButton);
        }
    }

    private void Clear() => MenuContainer.RemoveAllChildren();

    private void OnCategoryPressed(BaseButton.ButtonEventArgs ev, Category category)
    {
        _currentCategory = category.Name;

        var topLeft = ev.Button.GlobalRect.BottomLeft;

        topLeft.Y += 8;
        topLeft.X += 8;

        _popup.SetItems(category.Items);
        _popup.Open(UIBox2.FromDimensions(topLeft, new(100, 100)));
    }

    public record struct Category(LocalizedString Name, List<GlobalMenuPopup.Item> Items, bool IsIcon);
}
