name: YAML Linter

on:
  push:
    branches: [ master, staging, trying ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  build:
    name: YAML Linter
    if: github.actor != 'PJBot' && github.event.pull_request.draft == false && github.actor != 'DeltaV-Bot' && github.actor != 'SimpleStation14'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Setup Pkl
        run: |
          mkdir -p "$HOME/.local/bin"
          curl -L -o "$HOME/.local/bin/pkl" 'https://github.com/apple/pkl/releases/download/0.28.2/pkl-linux-amd64'
          chmod +x "$HOME/.local/bin/pkl"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          pkl --version
      - name: Setup submodule
        run: |
          git submodule update --init --recursive
      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5
      - name: Update Engine Submodules
        run: |
          cd RobustToolbox/
          git submodule update --init --recursive
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 9.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore /p:WarningsAsErrors= /m
      - name: Generate Typings
        run: chmod +x ./Scripts/sh/genTypings.sh && ./Scripts/sh/genTypings.sh
      - name: Pkl Eval
        run: chmod +x ./Scripts/sh/pklEval.sh && ./Scripts/sh/pklEval.sh
      - name: Run Linter
        run: dotnet run --project Content.YAMLLinter/Content.YAMLLinter.csproj --no-build
